"""empty message

Revision ID: 02c49b86a29b
Revises: e5ceb44accee
Create Date: 2026-09-10 15:53:57.890972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c49b86a29b'
down_revision: Union[str, Sequence[str], None] = 'e5ceb44accee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracurricularactivity', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracurricularactivity', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               nullable=False)

    # ### end Alembic commands ###
