"""empty message

Revision ID: 6a0904aef896
Revises: 8230aaede1b4
Create Date: 2026-09-11 11:21:26.562800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6a0904aef896'
down_revision: Union[str, Sequence[str], None] = '8230aaede1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_name'), ['name'], unique=True)

    op.create_table('childactivitylink',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['extracurricularactivity.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'activity_id')
    )
    with op.batch_alter_table('extracurricularactivity', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               nullable=False)
        batch_op.drop_column('child_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracurricularactivity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_name', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('day_of_week',
               nullable=True)

    op.drop_table('childactivitylink')
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_name'))

    op.drop_table('child')
    # ### end Alembic commands ###
