"""empty message

Revision ID: 8230aaede1b4
Revises: 02c49b86a29b
Create Date: 2026-09-11 10:24:53.253541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8230aaede1b4'
down_revision: Union[str, Sequence[str], None] = '02c49b86a29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracurricularactivity', schema=None) as batch_op:
        batch_op.alter_column('child_name',
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracurricularactivity', schema=None) as batch_op:
        batch_op.alter_column('child_name',
               nullable=False)

    # ### end Alembic commands ###
