"""empty message

Revision ID: 9d56a257f6c9
Revises: 6a0904aef896
Create Date: 2026-09-11 11:25:10.218388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9d56a257f6c9'
down_revision: Union[str, Sequence[str], None] = '6a0904aef896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracurricularactivity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_name', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracurricularactivity', schema=None) as batch_op:
        batch_op.drop_column('child_name')

    # ### end Alembic commands ###
