"""empty message

Revision ID: e5ceb44accee
Revises: 
Create Date: 2026-09-04 12:54:12.146138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e5ceb44accee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracurricularactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('child_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracurricularactivity')
    # ### end Alembic commands ###
